language: go
arch:
  - amd64
os:
  - linux
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - 1.17.x
env:
  - GO111MODULE=on
before_install:
  - go mod tidy
script:
  - make build-linux
  - make build-windows
  - make build-darwin
  - go test -v ./
