[main]
# 安装的插件
install = ["backup.so","tencnt_cos_upload.so","web_config.so","recover.so"]
# 循环的时间，即备份开始的时间
lopp_time = 7200

# 插件的配置由plugin.name.case组成,比如plugin.backup.file_path
[plugin.backup.file_path]
    log = "./log"
    static = "./static"
[plugin.upload.cos]
    sId = "1"
    sKey = "1"
    bucketUrl = "1"
    serviceUrl = "1"
