[project]
# 安装的插件
install = ["backup","upload","web_config","daemon","encrypt"]
# 循环的时间，即备份开始的时间
lopp_time = 7200

[project.log]
access_log = "./access.log"
error_log = "./error.log"

# 插件的配置由plugin.name.case组成,比如plugin.backup.file_path
[plugin.backup.file_path]
    # 项目根路径
    root = "./"
    # 静态资源的路径
    static = "./"
[plugin.backup.database]
    driver = "mysql"
    host = "localhost"
    port = "3306"
    user = "root"
    password = "root"
    databases = ["sys","mysql"]
[plugin.upload.cos]
    sId = "$ENV:COS_SID"
    sKey = "$ENV:COS_SKEY"
    bucketUrl = "$ENV:COS_BUCKET_URL"
    serviceUrl = "$ENV:COS_SERVICE_URL"
