[project]
# 安装的插件
install = ["backup","tencnt_cos_upload","web_config","daemon"]
# 循环的时间，即备份开始的时间
lopp_time = 7200

[project.log]
access_log = "./test/access.log"
error_log = "./test/error.log"

# 插件的配置由plugin.name.case组成,比如plugin.backup.file_path
[plugin.backup.file_path]
    # 项目根路径
    root = "/User/harder/html"
    # 静态资源的路径
    static = "/User/harder/static"
[plugin.backup.database]
    driver = "mysql"
    host = "localhost"
    port = "3306"
    user = "harder"
    password = "83nnfd.."
    databases = ["youyu"]
[plugin.upload.cos]
    sId = "1"
    sKey = "1"
    bucketUrl = "1"
    serviceUrl = "1"
