cloud_api = "COS" # COS / qiniu
save_name = "myweb"
save_time = 3600
save_time_pass = 72400

[bucket]
bucket_url = ""
secretid = ""
secretkey = ""
token = ""

[database]
ipaddr = ""
port = ""
user_name = ""
user_passwd = ""
db_name = ""
db_name2 = ""

[local]
web = ""
static = ""
log = ""

[web_config]
switch = "on" # 是否打开web配置
ipaddr = "127.0.0.1"
port = ":8080"
user_name = "admin"
user_passwd = "admin"

[encryption]
switch = ""
encrypt_mode = ""
aes = ""

[rsa]
pub_key = ""
pri_key = ""