name: Test

on:
  push:
    branches: [ main,dev ]
  pull_request:
    branches: [ main,dev ]

jobs:

  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ "1.17", "1.16", "1.15", "1.14" ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go_version}}
      - name: Tets-Env
        run: make test-env

      - name: Test
        run: make test
